sudo: false
env:
  - CC=clang CXX=clang++ npm_config_clang=1
language: node_js
node_js:
  - '5'
  - '4'
script:
  - 'npm run ci'
  - 'node test/all.js'
  - 'rm -f .eslint*'
  - 'npm_registry=https://registry.npmjs.com sh test/git.sh'
after_script:
  - 'npm i codecov && ./node_modules/.bin/codecov'
