sudo: false
env:
  - CC=clang CXX=clang++ npm_config_clang=1
language: node_js
node_js:
  - '5'
  - '4'
script:
  - 'npm run ci'
  - 'node test/all.js'
after_script:
  - 'npm i codecov.io && cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js'
