sudo: false
env:
  - CC=clang CXX=clang++ npm_config_clang=1
language: node_js
node_js:
  - '5'
  - '4'
script:
  - 'echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
  - 'npm run ci'
  - 'node test/all.js'
after_script:
  - 'npm i codecov && ./node_modules/.bin/codecov'
