sudo: false
env:
  - CC=clang CXX=clang++ npm_config_clang=1
language: node_js
node_js:
  - '5'
  - '4'
before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - 'npm run ci'
  - 'node test/all.js'
after_script:
  - 'npm i codecov && codecov'
